version: 0.1.0                                            

name: Deploy a ReactJS site to GitHub pages  
description: A stack to deploy a ReactJS app created by CRA to GitHub Pages              

branding:                                                # stack branding 
 icon: 'package'
 color: 'black'

inputs:                                                  # stack inputs 
  - name: NODE_VERSION                                   # stack input name
    default: v14.17.4                                    # stack input default value provided
    description: NODE_VERSION for nodejs stack           # stack input description
    validvalues:                                         # stack input valid values that can be selected
    - v14.17.4
    - v16.13.1
    
  - name: GITHUB_PAT
    description: GitHub PAT with repo and workflow permissions
    required: true
    is-secret: true

configs:
  repo-metadata:
    parameters:
      description: 'ReactJS App on GH pages'
      secrets: 
      - name: GH_PAT
        value: ${{inputs.GITHUB_PAT}}
      topics:
      - reactjs
      - github-pages

  branches:
    - name: main
      parameters:
        enforce-admins: true

  environments:
    - name: development
      parameters:
        protected-branches: false
        allowed-branch-rules:
          - main
          - releases/*

init:
  uses: "stack-init.yaml"
